name: mobile
description: Delego field operations and task platform (Flutter client).
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.9.0
  sqflite: ^2.4.2
  path: ^1.9.1
  geolocator: ^14.0.2
  image_picker: ^1.2.0
  flutter_secure_storage: ^9.2.4
  uuid: ^4.5.1
  socket_io_client: ^3.1.2
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/branding/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/app_icon.png
  adaptive_icon_background: '#0B0F14'
  adaptive_icon_foreground: assets/branding/app_icon.png

flutter_native_splash:
  color: '#0B0F14'
  image: assets/branding/app_icon.png
  android_12:
    color: '#0B0F14'
    image: assets/branding/app_icon.png
